#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Keiyo Nakayama
# SPDX-License-Identifier: BSD-3-Clause

import random
import sys

guess = (sys.argv[1])
def number_guessing_game(guess):
    ans = random.randint(1,100)
    guess = int(guess)

    print("数字を当てて!Guess The Number!（1~100)")


    if guess < ans:
        print("もっと大きいよ！Answer is Bigger!正解は:",ans)

    elif guess > ans:
        print("もっと小さいよ！Answer is Smaller!正解は:",ans)

    else:
        print("正解！")


number_guessing_game(guess)
