#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Keiyo Nakayama
# SPDX-License-Identifier: BSD-3-Clause

import random
import sys

guess = sys.stdin

for guess in sys.stdin:

    ans = random.randint(1,100)

    
    if guess < str(ans):
        print("もっと大きいよ！Answer is Bigger!正解は:",ans)

    elif guess > str(ans):
        print("もっと小さいよ！Answer is Smaller!正解は:",ans)

    elif guess == str(ans):
        print("正解！")

