#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Keiyo Nakayama
# SPDX-License-Identifier: BSD-3-Clause

import random
import sys


for guess in sys.stdin:
    
    guess = guess.strip()
    guess = int(guess)
    ans = random.randint(1,100)

    if guess < int(ans):
        print("もっと大きいよ! Answer is Bigger!正解は:",ans)

    elif guess > int(ans):
        print("もっと小さいよ! Answer is Smaller!正解は:",ans)

    elif guess == int(ans):
        print("正解! ")




